// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url:
      process.env["DATABASE_URL"] ??
      "postgresql://neondb_owner:npg_b1oTmSuv6Qyz@ep-soft-sea-aq1kmkj8-pooler.c-8.us-east-1.aws.neon.tech/neondb?channel_binding=require&sslmode=require",
  },
});
